[mssql_servers]
vm1 ansible_host=192.168.70.129 instance_name=instance1 vmware_name=devops_VM1
vm2 ansible_host=192.168.70.130 instance_name=instance2 vmware_name=devops_VM2

[mssql_servers:vars]
ansible_user=devops
ansible_ssh_private_key_file=/Users/srilaya/.ssh/id_rsa_mssql
ansible_connection=ssh
ansible_port=22
